import { CopyItAsset, CopyItPickAsset } from './copyit-asset';
import { TabResponse } from './copyitConfigTabs';
import { CopyItDetailEnvelopes } from './copyItEnvelopes';
import { CopyItDetailFinishings } from './copyItFinishings';
import { CopyItDetailOversizedCopies } from './copyItOversizedCopies';
import { CopyItDetailPaperColors } from './copyItPaperColors';
import { CopyItDetailPaperSizes } from './copyItPaperSizes';
import { CopyItDetailPaperStocks } from './copyItPaperStocks';
import { CopyItDetailReproductionTypes } from './copyItReproductionTypes';
import { FileResponse } from './fileResponse';

/** Model class for CopyIt Response */
export class CopyItResponse {
    public copyItNumber?: number;
    public clientId?: number;
    public companyName?: string;
    public accountNumber?: boolean;
    public isPrepopulateAccountNumber?: boolean;
    public associateId?: number;
    public associateName?: string;
    public requestForId?: number;
    public requestForName?: string;
    public emailAddress?: string;
    public phoneNumber?: string;
    public clientAccountId?: number;
    public accountNo?: string;
    public departmentName?: string;
    public jobname?: string;
    public isPriceQuote?: boolean;
    public isProof?: boolean;
    public dueDate?: string;
    public dueTime?: string;
    public noOfPages?: number;
    public noOfCopies?: number;
    public reproductionTypes?: CopyItDetailReproductionTypes[];
    public tab?: TabResponse;
    public finishings?: CopyItDetailFinishings[];
    public envelopes?: CopyItDetailEnvelopes[];
    public oversizedCopies?: CopyItDetailOversizedCopies[];
    public paperSizes?: CopyItDetailPaperSizes[];
    public paperColors?: CopyItDetailPaperColors[];
    public paperStocks?: CopyItDetailPaperStocks[];
    public rateRequestTypeId?: number;
    public deliveredTo?: string;
    public shippingServiceId?: number;
    public shippingService?: string;
    public shippingOptionId?: number;
    public shippingOptionValue?: string;
    public copyItStatusId?: number;
    public copyItStatus?: string;
    public files?: FileResponse[];
    public fileOptionId?: number;
    public shareFilePath?: string;
    public priorityId?: number;
    public completedDate?: string;
    public completedTime?: string;
    public isQualityCheck?: boolean;
    public pickAssets: CopyItPickAsset[];
    public assets: CopyItAsset[];
}
